# UNTESTED
[metadata]
name = "docker-images"
description = "A channel to select from Docker images"
requirements = ["docker", "jq"]

[source]
command = "bash -c 'docker images --format \"{{.Repository}}:{{.Tag}} {{.ID}}\"'"
output = "{split: :-1}"


[preview]
command = "bash -c 'docker image inspect \"{split: :-1}\" | jq -C'"
