[metadata]
name = "dotfiles"
description = "A channel to select from your user's dotfiles"
requirements = ["fd", "bat"]

[source]
command = "bash -c 'fd -t f . \"$HOME/.config\"'"


[preview]
command = "bat -n --color=always '{}'"
