[metadata]
name = "zsh-history"
description = "A channel to select from your zsh history"
requirements = ["zsh"]

[source]
command = "zsh -c 'if [ -n \"$HISTFILE\" ]; then histfile=\"$HISTFILE\"; else histfile=\"$HOME/.zsh_history\"; fi; sed \"1!G;h;$!d\" \"$histfile\"'"
display = "{split:;:1..}"
output = "{split:;:1..}"
